openapi: 3.0.3
info:
  title: 'online-store-api'
  description: 'A REST API for an online store'
  version: 0.0.1

components:
  schemas:
    Product:
      properties:
        name:
          type: string
          minimum: 3
          maximum: 20
        description:
          type: string
          minimum: 3
          maximum: 255
        price:
          type: number
        image:
          type: string
          format: binary
      required:
        - name
    ShoppingCart:
      properties:
        products:
          type: array
          items:
            $ref: '#/components/schemas/Product'

paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: Returns all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Returns the created product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
  /products{productId}:
    parameters:
      - in: path
        name: productId
        required: true
        schema:
          type: integer
          minimum: 1
        description: The ID of the product
    delete:
      summary: Deletes a product
      description: Deletes a product with a specified ID
      responses:
        '204':
          description: Product deleted
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
  /users/{userId}/shoppingCart:
    parameters:
      - in: path
        name: userId
        required: true
        schema:
          type: integer
          minimum: 1
        description: The ID of the shopping cart's user
    get:
      summary: Get a user's shopping cart
      responses:
        '200':
          description: Returns a user's shopping cart
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/ShoppingCart'
        '404':
          description: Not Found
        '500':
          description: Internal Server Error

