openapi: 3.0.3
info:
  title: 'online-store-api'
  description: 'A REST API for an online store'
  version: 0.0.1

components:
  schemas:
    Product:
      properties:
        name:
          type: string
          minimum: 3
          maximum: 20
        description:
          type: string
          minimum: 3
          maximum: 255
        price:
          type: number
        image:
          type: string
          format: binary
      required:
        - name
paths:
  /products:
    get:
      summary: Get all products
      responses:
        '200':
          description: Returns all products
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
        '404':
          description: Not Found
        '500':
          description: Internal Server Error
    post:
      summary: Create a product
      requestBody:
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/Product'
      responses:
        '201':
          description: Returns the created product
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/Product'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error
